import { nanoid } from "nanoid";
export const filterData = [
  {
    id: nanoid(),
    label: "Department",
    list: [
      { id: nanoid(), label: "men", count: 300 },
      { id: nanoid(), label: "women", count: 350 },
      { id: nanoid(), label: "kids", count: 460 },
    ],
  },

  {
    id: nanoid(),
    label: "Categories",
    list: [
      { id: nanoid(), label: "casual wear", count: 300 },
      { id: nanoid(), label: "formal wear", count: 350 },
      { id: nanoid(), label: "westernwear", count: 460 },
      { id: nanoid(), label: "Indian anf Fusion Wear", count: 460 },
      { id: nanoid(), label: "boys", count: 460 },
      { id: nanoid(), label: "girls", count: 460 },
    ],
  },

  {
    id: nanoid(),
    label: "Subcategories",
    list: [
      { id: nanoid(), label: "shirts", count: 567 },
      { id: nanoid(), label: "tops", count: 80 },
      { id: nanoid(), label: "tops and tunics", count: 89 },
      { id: nanoid(), label: "kurtas", count: 89 },
      { id: nanoid(), label: "trousers", count: 89 },
      { id: nanoid(), label: "jackets", count: 89 },
    ],
  },

  {
    id: nanoid(),
    label: "Brands",
    list: [
      { id: nanoid(), label: "allen solly", count: 376 },
      { id: nanoid(), label: "arrow", count: 90 },
      { id: nanoid(), label: "peter england", count: 460 },
      { id: nanoid(), label: "peter england", count: 460 },
      { id: nanoid(), label: "peter england", count: 460 },
      { id: nanoid(), label: "campus sutra", count: 460 },
      { id: nanoid(), label: "vastrado", count: 460 },
      { id: nanoid(), label: "h&m", count: 460 },
      { id: nanoid(), label: "peter england", count: 460 },
    ],
  },
  {
    id: nanoid(),
    label: "Gender",
    list: [
      { id: nanoid(), label: "men", count: 376 },
      { id: nanoid(), label: "women", count: 90 },
      { id: nanoid(), label: "boys", count: 460 },
      { id: nanoid(), label: "girls", count: 460 },
    ],
  },
  {
    id: nanoid(),
    label: "Size",
    list: [
      { id: nanoid(), label: "S", count: 376 },
      { id: nanoid(), label: "M", count: 90 },
      { id: nanoid(), label: "L", count: 460 },
      { id: nanoid(), label: "XL", count: 460 },
      { id: nanoid(), label: "XXL", count: 460 },
      { id: nanoid(), label: "3 - 4 Years", count: 460 },
      { id: nanoid(), label: "5 - 6 Years", count: 460 },
      { id: nanoid(), label: "7 - 8 Years", count: 460 },
      { id: nanoid(), label: "8 - 9 Years", count: 460 },
      { id: nanoid(), label: "10 - 11 Years", count: 460 },
      { id: nanoid(), label: "12 - 13 Years", count: 460 },
    ],
  },
  {
    id: nanoid(),
    label: "Size",
    list: [
      { id: nanoid(), label: "S", count: 376 },
      { id: nanoid(), label: "M", count: 90 },
      { id: nanoid(), label: "L", count: 460 },
      { id: nanoid(), label: "XL", count: 460 },
      { id: nanoid(), label: "XXL", count: 460 },
      { id: nanoid(), label: "3 - 4 Years", count: 460 },
      { id: nanoid(), label: "5 - 6 Years", count: 460 },
      { id: nanoid(), label: "7 - 8 Years", count: 460 },
      { id: nanoid(), label: "8 - 9 Years", count: 460 },
      { id: nanoid(), label: "10 - 11 Years", count: 460 },
      { id: nanoid(), label: "12 - 13 Years", count: 460 },
    ],
  },
  {
    id: nanoid(),
    label: "Price",
    list: [
      { id: nanoid(), label: "0 - 500", count: 376 },
      { id: nanoid(), label: "500 - 1000", count: 90 },
      { id: nanoid(), label: "1000 - 1500", count: 460 },
      { id: nanoid(), label: "1500 - 2000", count: 460 },
      { id: nanoid(), label: "2000 - 2500", count: 460 },
      { id: nanoid(), label: "2500 - 3000", count: 460 },
      { id: nanoid(), label: "3000 - 3500", count: 460 },
      { id: nanoid(), label: "3500 - 4000", count: 460 },
      { id: nanoid(), label: "4000 - 4500", count: 460 },
      { id: nanoid(), label: "4500 - 5000", count: 460 },
      { id: nanoid(), label: "5000 - 5500", count: 460 },
      { id: nanoid(), label: "5500 - 6000", count: 460 },
      { id: nanoid(), label: "6000 - Above", count: 460 },
    ],
  },
  {
    id: nanoid(),
    label: "Discount",
    list: [
      { id: nanoid(), label: "80", count: 376 },
      { id: nanoid(), label: "70", count: 376 },
      { id: nanoid(), label: "60", count: 376 },
      { id: nanoid(), label: "50", count: 90 },
      { id: nanoid(), label: "50", count: 90 },
      { id: nanoid(), label: "40", count: 90 },
      { id: nanoid(), label: "30", count: 90 },
      { id: nanoid(), label: "20", count: 90 },
      { id: nanoid(), label: "10", count: 90 },
      { id: nanoid(), label: "5", count: 90 },
    ],
  },
  {
    id: nanoid(),
    label: "Color",
    list: [
      { id: nanoid(), label: "Black", count: 376 },
      { id: nanoid(), label: "Blue", count: 376 },
      { id: nanoid(), label: "Yellow", count: 376 },
      { id: nanoid(), label: "Red", count: 376 },
      { id: nanoid(), label: "White", count: 376 },
      { id: nanoid(), label: "Pink", count: 376 },
      { id: nanoid(), label: "Brown", count: 376 },
      { id: nanoid(), label: "Green", count: 376 },
      { id: nanoid(), label: "Purple", count: 376 },
      { id: nanoid(), label: "Peach", count: 376 },
      { id: nanoid(), label: "Grey", count: 376 },
    ],
  },
  {
    id: nanoid(),
    label: "Fabric",
    list: [
      { id: nanoid(), label: "Cotton", count: 376 },
      { id: nanoid(), label: "Linen", count: 142 },
      { id: nanoid(), label: "Polyester", count: 289 },
      { id: nanoid(), label: "Silk Blend", count: 87 },
      { id: nanoid(), label: "Rayon", count: 114 },
      { id: nanoid(), label: "Wool", count: 39 },
      { id: nanoid(), label: "Viscose", count: 73 },
      { id: nanoid(), label: "Denim", count: 98 },
      { id: nanoid(), label: "Nylon", count: 56 },
      { id: nanoid(), label: "Khadi", count: 21 },
      { id: nanoid(), label: "Acrylic", count: 47 },
    ],
  },
];
