export const productData = [
  {
    title: "Men Slim Fit Solid Shirt",
    brand: "HIGHLANDER",
    price: 1499,
    discountedPrice: 449,
    discount: "71%",
    color: "Solid",
    size: ["M", "L", "XL"],
    imgUrl: "https://i1.flipkart.com/image1.jpg",
  },
  {
    title: "Men Regular Fit Checkered Shirt",
    brand: "THE BEAR HOUSE",
    price: 1999,
    discountedPrice: 599,
    discount: "71%",
    color: "Checkered",
    size: ["S", "M"],
    imgUrl: "https://i2.flipkart.com/image2.jpg",
  },
  {
    title: "Men Slim Fit Striped Shirt",
    brand: "METRONAUT",
    price: 2499,
    discountedPrice: 749,
    discount: "71%",
    color: "Striped",
    size: ["L", "XL"],
    imgUrl: "https://i3.flipkart.com/image3.jpg",
  },
  {
    title: "Men Regular Fit Printed Shirt",
    brand: "Allen Solly",
    price: 2999,
    discountedPrice: 899,
    discount: "70%",
    color: "Printed",
    size: ["S", "M", "L", "XL"],
    imgUrl: "https://i4.flipkart.com/image4.jpg",
  },
  {
    title: "Men Slim Fit Solid Shirt",
    brand: "Dennis Lingo",
    price: 3499,
    discountedPrice: 1049,
    discount: "70%",
    color: "Solid",
    size: ["M", "L", "XL"],
    imgUrl: "https://i5.flipkart.com/image5.jpg",
  },
  {
    title: "Men Regular Fit Checkered Shirt",
    brand: "U.S. Polo Assn.",
    price: 1499,
    discountedPrice: 449,
    discount: "71%",
    color: "Checkered",
    size: ["S", "M"],
    imgUrl: "https://i6.flipkart.com/image6.jpg",
  },
  {
    title: "Men Slim Fit Striped Shirt",
    brand: "Louis Philippe",
    price: 1999,
    discountedPrice: 599,
    discount: "71%",
    color: "Striped",
    size: ["L", "XL"],
    imgUrl: "https://i7.flipkart.com/image7.jpg",
  },
  {
    title: "Men Regular Fit Printed Shirt",
    brand: "Peter England",
    price: 2499,
    discountedPrice: 749,
    discount: "71%",
    color: "Printed",
    size: ["S", "M", "L", "XL"],
    imgUrl: "https://i8.flipkart.com/image8.jpg",
  },
  {
    title: "Men Slim Fit Solid Shirt",
    brand: "Van Heusen",
    price: 2999,
    discountedPrice: 899,
    discount: "70%",
    color: "Solid",
    size: ["M", "L", "XL"],
    imgUrl: "https://i9.flipkart.com/image9.jpg",
  },
  {
    title: "Men Regular Fit Checkered Shirt",
    brand: "Park Avenue",
    price: 3499,
    discountedPrice: 1049,
    discount: "70%",
    color: "Checkered",
    size: ["S", "M"],
    imgUrl: "https://i10.flipkart.com/image10.jpg",
  },
  {
    title: "Men Slim Fit Striped Shirt",
    brand: "HIGHLANDER",
    price: 1499,
    discountedPrice: 449,
    discount: "71%",
    color: "Striped",
    size: ["L", "XL"],
    imgUrl: "https://i11.flipkart.com/image11.jpg",
  },
  {
    title: "Men Regular Fit Printed Shirt",
    brand: "THE BEAR HOUSE",
    price: 1999,
    discountedPrice: 599,
    discount: "71%",
    color: "Printed",
    size: ["S", "M", "L", "XL"],
    imgUrl: "https://i12.flipkart.com/image12.jpg",
  },
  {
    title: "Men Slim Fit Solid Shirt",
    brand: "METRONAUT",
    price: 2499,
    discountedPrice: 749,
    discount: "71%",
    color: "Solid",
    size: ["M", "L", "XL"],
    imgUrl: "https://i13.flipkart.com/image13.jpg",
  },
  {
    title: "Men Regular Fit Checkered Shirt",
    brand: "Allen Solly",
    price: 2999,
    discountedPrice: 899,
    discount: "70%",
    color: "Checkered",
    size: ["S", "M"],
    imgUrl: "https://i14.flipkart.com/image14.jpg",
  },
  {
    title: "Men Slim Fit Striped Shirt",
    brand: "Dennis Lingo",
    price: 3499,
    discountedPrice: 1049,
    discount: "70%",
    color: "Striped",
    size: ["L", "XL"],
    imgUrl: "https://i15.flipkart.com/image15.jpg",
  },
  {
    title: "Men Regular Fit Printed Shirt",
    brand: "U.S. Polo Assn.",
    price: 1499,
    discountedPrice: 449,
    discount: "71%",
    color: "Printed",
    size: ["S", "M", "L", "XL"],
    imgUrl: "https://i16.flipkart.com/image16.jpg",
  },
  {
    title: "Men Slim Fit Solid Shirt",
    brand: "Louis Philippe",
    price: 1999,
    discountedPrice: 599,
    discount: "71%",
    color: "Solid",
    size: ["M", "L", "XL"],
    imgUrl: "https://i17.flipkart.com/image17.jpg",
  },
  {
    title: "Men Regular Fit Checkered Shirt",
    brand: "Peter England",
    price: 2499,
    discountedPrice: 749,
    discount: "71%",
    color: "Checkered",
    size: ["S", "M"],
    imgUrl: "https://i18.flipkart.com/image18.jpg",
  },
  {
    title: "Men Slim Fit Striped Shirt",
    brand: "Van Heusen",
    price: 2999,
    discountedPrice: 899,
    discount: "70%",
    color: "Striped",
    size: ["L", "XL"],
    imgUrl: "https://i19.flipkart.com/image19.jpg",
  },
  {
    title: "Men Regular Fit Printed Shirt",
    brand: "Park Avenue",
    price: 3499,
    discountedPrice: 1049,
    discount: "70%",
    color: "Printed",
    size: ["S", "M", "L", "XL"],
    imgUrl: "https://i20.flipkart.com/image20.jpg",
  },
  {
    title: "Men Slim Fit Solid Shirt",
    brand: "HIGHLANDER",
    price: 1499,
    discountedPrice: 449,
    discount: "71%",
    color: "Solid",
    size: ["M", "L", "XL"],
    imgUrl: "https://i21.flipkart.com/image21.jpg",
  },
  {
    title: "Men Regular Fit Checkered Shirt",
    brand: "THE BEAR HOUSE",
    price: 1999,
    discountedPrice: 599,
    discount: "71%",
    color: "Checkered",
    size: ["S", "M"],
    imgUrl: "https://i22.flipkart.com/image22.jpg",
  },
  {
    title: "Men Slim Fit Striped Shirt",
    brand: "METRONAUT",
    price: 2499,
    discountedPrice: 749,
    discount: "71%",
    color: "Striped",
    size: ["L", "XL"],
    imgUrl: "https://i23.flipkart.com/image23.jpg",
  },
  {
    title: "Men Regular Fit Printed Shirt",
    brand: "Allen Solly",
    price: 2999,
    discountedPrice: 899,
    discount: "70%",
    color: "Printed",
    size: ["S", "M", "L", "XL"],
    imgUrl: "https://i24.flipkart.com/image24.jpg",
  },
  {
    title: "Men Slim Fit Solid Shirt",
    brand: "Dennis Lingo",
    price: 3499,
    discountedPrice: 1049,
    discount: "70%",
    color: "Solid",
    size: ["M", "L", "XL"],
    imgUrl: "https://i25.flipkart.com/image25.jpg",
  },
  {
    title: "Men Regular Fit Checkered Shirt",
    brand: "U.S. Polo Assn.",
    price: 1499,
    discountedPrice: 449,
    discount: "71%",
    color: "Checkered",
    size: ["S", "M"],
    imgUrl: "https://i26.flipkart.com/image26.jpg",
  },
  {
    title: "Men Slim Fit Striped Shirt",
    brand: "Louis Philippe",
    price: 1999,
    discountedPrice: 599,
    discount: "71%",
    color: "Striped",
    size: ["L", "XL"],
    imgUrl: "https://i27.flipkart.com/image27.jpg",
  },
  {
    title: "Men Regular Fit Printed Shirt",
    brand: "Peter England",
    price: 2499,
    discountedPrice: 749,
    discount: "71%",
    color: "Printed",
    size: ["S", "M", "L", "XL"],
    imgUrl: "https://i28.flipkart.com/image28.jpg",
  },
  {
    title: "Men Slim Fit Solid Shirt",
    brand: "Van Heusen",
    price: 2999,
    discountedPrice: 899,
    discount: "70%",
    color: "Solid",
    size: ["M", "L", "XL"],
    imgUrl: "https://i29.flipkart.com/image29.jpg",
  },
  {
    title: "Men Regular Fit Checkered Shirt",
    brand: "Park Avenue",
    price: 3499,
    discountedPrice: 1049,
    discount: "70%",
    color: "Checkered",
    size: ["S", "M"],
    imgUrl: "https://i30.flipkart.com/image30.jpg",
  },
  {
    title: "Men Slim Fit Solid Shirt",
    brand: "HIGHLANDER",
    price: 1499,
    discountedPrice: 449,
    discount: "71%",
    color: "Solid",
    size: ["M", "L", "XL"],
    imgUrl: "https://i1.flipkart.com/image1.jpg",
  },
  {
    title: "Men Regular Fit Checkered Shirt",
    brand: "THE BEAR HOUSE",
    price: 1999,
    discountedPrice: 599,
    discount: "71%",
    color: "Checkered",
    size: ["S", "M"],
    imgUrl: "https://i2.flipkart.com/image2.jpg",
  },
  {
    title: "Men Slim Fit Striped Shirt",
    brand: "METRONAUT",
    price: 2499,
    discountedPrice: 749,
    discount: "71%",
    color: "Striped",
    size: ["L", "XL"],
    imgUrl: "https://i3.flipkart.com/image3.jpg",
  },
  {
    title: "Men Regular Fit Printed Shirt",
    brand: "Allen Solly",
    price: 2999,
    discountedPrice: 899,
    discount: "70%",
    color: "Printed",
    size: ["S", "M", "L", "XL"],
    imgUrl: "https://i4.flipkart.com/image4.jpg",
  },
  {
    title: "Men Slim Fit Solid Shirt",
    brand: "Dennis Lingo",
    price: 3499,
    discountedPrice: 1049,
    discount: "70%",
    color: "Solid",
    size: ["M", "L", "XL"],
    imgUrl: "https://i5.flipkart.com/image5.jpg",
  },
  {
    title: "Men Regular Fit Checkered Shirt",
    brand: "U.S. Polo Assn.",
    price: 1499,
    discountedPrice: 449,
    discount: "71%",
    color: "Checkered",
    size: ["S", "M"],
    imgUrl: "https://i6.flipkart.com/image6.jpg",
  },
  {
    title: "Men Slim Fit Striped Shirt",
    brand: "Louis Philippe",
    price: 1999,
    discountedPrice: 599,
    discount: "71%",
    color: "Striped",
    size: ["L", "XL"],
    imgUrl: "https://i7.flipkart.com/image7.jpg",
  },
  {
    title: "Men Regular Fit Printed Shirt",
    brand: "Peter England",
    price: 2499,
    discountedPrice: 749,
    discount: "71%",
    color: "Printed",
    size: ["S", "M", "L", "XL"],
    imgUrl: "https://i8.flipkart.com/image8.jpg",
  },
  {
    title: "Men Slim Fit Solid Shirt",
    brand: "Van Heusen",
    price: 2999,
    discountedPrice: 899,
    discount: "70%",
    color: "Solid",
    size: ["M", "L", "XL"],
    imgUrl: "https://i9.flipkart.com/image9.jpg",
  },
  {
    title: "Men Regular Fit Checkered Shirt",
    brand: "Park Avenue",
    price: 3499,
    discountedPrice: 1049,
    discount: "70%",
    color: "Checkered",
    size: ["S", "M"],
    imgUrl: "https://i10.flipkart.com/image10.jpg",
  },
  {
    title: "Men Slim Fit Striped Shirt",
    brand: "HIGHLANDER",
    price: 1499,
    discountedPrice: 449,
    discount: "71%",
    color: "Striped",
    size: ["L", "XL"],
    imgUrl: "https://i11.flipkart.com/image11.jpg",
  },
  {
    title: "Men Regular Fit Printed Shirt",
    brand: "THE BEAR HOUSE",
    price: 1999,
    discountedPrice: 599,
    discount: "71%",
    color: "Printed",
    size: ["S", "M", "L", "XL"],
    imgUrl: "https://i12.flipkart.com/image12.jpg",
  },
  {
    title: "Men Slim Fit Solid Shirt",
    brand: "METRONAUT",
    price: 2499,
    discountedPrice: 749,
    discount: "71%",
    color: "Solid",
    size: ["M", "L", "XL"],
    imgUrl: "https://i13.flipkart.com/image13.jpg",
  },
  {
    title: "Men Regular Fit Checkered Shirt",
    brand: "Allen Solly",
    price: 2999,
    discountedPrice: 899,
    discount: "70%",
    color: "Checkered",
    size: ["S", "M"],
    imgUrl: "https://i14.flipkart.com/image14.jpg",
  },
  {
    title: "Men Slim Fit Striped Shirt",
    brand: "Dennis Lingo",
    price: 3499,
    discountedPrice: 1049,
    discount: "70%",
    color: "Striped",
    size: ["L", "XL"],
    imgUrl: "https://i15.flipkart.com/image15.jpg",
  },
  {
    title: "Men Regular Fit Printed Shirt",
    brand: "U.S. Polo Assn.",
    price: 1499,
    discountedPrice: 449,
    discount: "71%",
    color: "Printed",
    size: ["S", "M", "L", "XL"],
    imgUrl: "https://i16.flipkart.com/image16.jpg",
  },
  {
    title: "Men Slim Fit Solid Shirt",
    brand: "Louis Philippe",
    price: 1999,
    discountedPrice: 599,
    discount: "71%",
    color: "Solid",
    size: ["M", "L", "XL"],
    imgUrl: "https://i17.flipkart.com/image17.jpg",
  },
  {
    title: "Men Regular Fit Checkered Shirt",
    brand: "Peter England",
    price: 2499,
    discountedPrice: 749,
    discount: "71%",
    color: "Checkered",
    size: ["S", "M"],
    imgUrl: "https://i18.flipkart.com/image18.jpg",
  },
  {
    title: "Men Slim Fit Striped Shirt",
    brand: "Van Heusen",
    price: 2999,
    discountedPrice: 899,
    discount: "70%",
    color: "Striped",
    size: ["L", "XL"],
    imgUrl: "https://i19.flipkart.com/image19.jpg",
  },
  {
    title: "Men Regular Fit Printed Shirt",
    brand: "Park Avenue",
    price: 3499,
    discountedPrice: 1049,
    discount: "70%",
    color: "Printed",
    size: ["S", "M", "L", "XL"],
    imgUrl: "https://i20.flipkart.com/image20.jpg",
  },
  {
    title: "Men Slim Fit Solid Shirt",
    brand: "HIGHLANDER",
    price: 1499,
    discountedPrice: 449,
    discount: "71%",
    color: "Solid",
    size: ["M", "L", "XL"],
    imgUrl: "https://i21.flipkart.com/image21.jpg",
  },
  {
    title: "Men Regular Fit Checkered Shirt",
    brand: "THE BEAR HOUSE",
    price: 1999,
    discountedPrice: 599,
    discount: "71%",
    color: "Checkered",
    size: ["S", "M"],
    imgUrl: "https://i22.flipkart.com/image22.jpg",
  },
  {
    title: "Men Slim Fit Striped Shirt",
    brand: "METRONAUT",
    price: 2499,
    discountedPrice: 749,
    discount: "71%",
    color: "Striped",
    size: ["L", "XL"],
    imgUrl: "https://i23.flipkart.com/image23.jpg",
  },
  {
    title: "Men Regular Fit Printed Shirt",
    brand: "Allen Solly",
    price: 2999,
    discountedPrice: 899,
    discount: "70%",
    color: "Printed",
    size: ["S", "M", "L", "XL"],
    imgUrl: "https://i24.flipkart.com/image24.jpg",
  },
  {
    title: "Men Slim Fit Solid Shirt",
    brand: "Dennis Lingo",
    price: 3499,
    discountedPrice: 1049,
    discount: "70%",
    color: "Solid",
    size: ["M", "L", "XL"],
    imgUrl: "https://i25.flipkart.com/image25.jpg",
  },
  {
    title: "Men Regular Fit Checkered Shirt",
    brand: "U.S. Polo Assn.",
    price: 1499,
    discountedPrice: 449,
    discount: "71%",
    color: "Checkered",
    size: ["S", "M"],
    imgUrl: "https://i26.flipkart.com/image26.jpg",
  },
  {
    title: "Men Slim Fit Striped Shirt",
    brand: "Louis Philippe",
    price: 1999,
    discountedPrice: 599,
    discount: "71%",
    color: "Striped",
    size: ["L", "XL"],
    imgUrl: "https://i27.flipkart.com/image27.jpg",
  },
  {
    title: "Men Regular Fit Printed Shirt",
    brand: "Peter England",
    price: 2499,
    discountedPrice: 749,
    discount: "71%",
    color: "Printed",
    size: ["S", "M", "L", "XL"],
    imgUrl: "https://i28.flipkart.com/image28.jpg",
  },
  {
    title: "Men Slim Fit Solid Shirt",
    brand: "Van Heusen",
    price: 2999,
    discountedPrice: 899,
    discount: "70%",
    color: "Solid",
    size: ["M", "L", "XL"],
    imgUrl: "https://i29.flipkart.com/image29.jpg",
  },
  {
    title: "Men Regular Fit Checkered Shirt",
    brand: "Park Avenue",
    price: 3499,
    discountedPrice: 1049,
    discount: "70%",
    color: "Checkered",
    size: ["S", "M"],
    imgUrl: "https://i30.flipkart.com/image30.jpg",
  },
];
